---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth1:
      addresses:
      - 192.168.245.1/30
      routes:
      - to: 0.0.0.0/0
        via: 192.168.245.2
    eth2:
      addresses:
      - 192.168.56.11/24